[WIP] LVM内存与字节码文档
ChinaCreators/LHL pull request #3
Opened 2018-05-08 05:06 UTC by xsun2001

# LVM内存与字节码文档补全计划

#2 

此PR处于WIP(Work In Progress)阶段，请不要将它合并到master分支。

2018-05-08 09:21 UTC, creatorlxd requested changes
我觉得没有必要有引用类型，在指令层次支持指令跳转就够了

2018-05-08 14:24 UTC, xsun2001 commented
@creatorlxd 这个引用可能和你想的不一样，请在我写完引用的文档后提出详细的建议

2018-05-09 12:30 UTC, creatorlxd commented
为什么不直接在指令中使用地址呢？
我看不出应用有什么意义？
除非你指令不用地址做参数。

2018-05-10 04:11 UTC, xsun2001 commented
指令就是堆内存地址......
只是换一个名字而已，可能我写的不怎么明白，导致你出现了一些误解......

2018-05-10 09:41 UTC, creatorlxd commented
`指令就是堆内存地址`???
我不明白是什么意思
@xsun2001

2018-05-10 16:10 UTC, xsun2001 commented
呃啊写错了，抱歉
应该是引用就是堆内存地址

2018-05-11 04:20 UTC, creatorlxd commented
。。。。。。

2018-05-11 04:21 UTC, creatorlxd commented
那目前的memory_address部分是不用改的

2018-07-24 10:34 UTC, xsun2001 commented
Closing because it isn't useful anymore.

2018-07-24 10:34 UTC, closed without merging

2018-07-24 10:35 UTC, xsun2001 commented
As a kind of reference, this brunch won't be closed.